[package]
name = "ChartExtractor-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
imageproc = "0.25.0"
ndarray = "0.16.1"
ort = "2.0.0-rc.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
walkdir = "2.5.0"
